In [1]:
# Data Processing
import numpy as np
import pandas as pd

# Datetime operations
from datetime import datetime as dt
from datetime import timedelta as td

# Visualisation
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
PATH = r"./data/"

# Data Downloading
sales_df = pd.read_csv(PATH + "shop_sales" + ".csv")
dates_df = pd.read_csv(PATH + "shop_sales_dates" + ".csv")
price_df = pd.read_csv(PATH + "shop_sales_prices" + ".csv")

# Create General Data Frame
link_df = dates_df[["date_id", "wm_yr_wk", "date"]].copy()
link_df = sales_df.merge(link_df, how="left", on=["date_id"])
link_df = link_df.merge(price_df, how="left", on=["store_id", "item_id", "wm_yr_wk"])
df = link_df[["date", "store_id", "item_id", "cnt", "sell_price"]].copy()

In [3]:
df

             date store_id      item_id  cnt  sell_price
0      2011-01-29  STORE_2  STORE_2_085    3        1.00
1      2011-01-30  STORE_2  STORE_2_085    8        1.00
2      2011-01-31  STORE_2  STORE_2_085    0        1.00
3      2011-02-01  STORE_2  STORE_2_085    3        1.00
4      2011-02-02  STORE_2  STORE_2_085    0        1.00
...           ...      ...          ...  ...         ...
81850  2016-01-17  STORE_1  STORE_1_727    2        4.48
81851  2016-01-18  STORE_1  STORE_1_727    3        4.48
81852  2016-01-19  STORE_1  STORE_1_727    1        4.48
81853  2016-01-20  STORE_1  STORE_1_727    4        4.48
81854  2016-01-21  STORE_1  STORE_1_727    2        4.48

[81855 rows x 5 columns]